services:
  chatbot_api:
    build: .
    container_name: portfolio_chatbot_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./src:/app/src          # NUEVO: Sincroniza tu código en tiempo real
      - ./config:/app/config    # NUEVO: Sincroniza tus prompts en tiempo real
    restart: unless-stopped